version: '3'
services:
  sqlserver:
    container_name: sqlserver_blogapi
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "HW(4D.*]`0TJ}|jQ,OT~?}KR:U6GXf5|LlTN3T]G"
      ACCEPT_EULA: "Y"
    restart: always
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
#    volumes:
#      - ./sqlserver/data:/var/opt/mssql/data
#      - ./sqlserver/log:/var/opt/mssql/log
  seq:
    container_name: seq_blogapi
    image: datalust/seq:2023.4
    ports:
      - '8081:80'
      - '5342:5341'
    restart: always
    environment:
      ACCEPT_EULA: "Y"
#    volumes:
#      - ./seq/:/data